### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by circuitb** [everoneishappy/InstanceNoodles#1]
hello Kyle,

just found there's a missing module
\modules\RandomShifts (Kyle).v4p" 
in
https://github.com/everoneishappy/InstanceNoodles/blob/master/nodes/modules/Compute/3D%20Buffer/Verlet%20(3D%20Buffer)/Verlet%20(3D%20Buffer)%20help.v4p

ps: seems the new Dx11  pack v1.0.0 introduce a lot of issues with the current InstanceNoodles!?

take care
C

**Comment by everyoneishappy** [comment]
Hey sorry for late response!  Seems the notification email got a bit buried...

Thanks help patch is easy fix.  How about the more general issues you are mentioning?  can you give some details/examples?  The pack has been a bit neglected tbh but in the next couple of months will be doing a large overhaul, so keen to hear if your issues are persisting.

**Comment by circuitb** [comment]
hi,
the issue is fixed now with the last dx11 pack, it guess it was related to the DynamicBuffer preferred default type!
