### ISSUE TITLE
Cross Node Only handles to the power of 3?

### ISSUE THREAD

**Issue by YanYas** [everoneishappy/InstanceNoodles#3]
Hi @everyoneishappy. I'm trying to make stack of boxes my translate node seems to output only cubed numbers. Is this how it is supposed to work? Could it be a hardware issue (Nvidia GTX 1070)?

![noodlestuff](https://user-images.githubusercontent.com/9497052/34847825-872540d2-f714-11e7-89f5-5778ac5a703f.PNG)

[NoodleQuestioins.zip](https://github.com/everyoneishappy/InstanceNoodles/files/1624140/NoodleQuestioins.zip)

**Comment by everyoneishappy** [comment]
Looks like a bug in the shader.  Try this?  https://github.com/everyoneishappy/InstanceNoodles/commit/ce071f00cdff6b63575854e1d1112132ccd388c9

**Comment by YanYas** [comment]
All good, thanks!
