### ISSUE TITLE
the miter example is missing files

### ISSUE THREAD

**Issue by wirmachenbunt** [everoneishappy/InstanceNoodles#4]
InstanceNoodles\nodes\modules\DX11.Layer\LineBuffered (DX11.Layer)

**Comment by everyoneishappy** [comment]
What are you missing?  can't confirm here.

**Comment by wirmachenbunt** [comment]
![worksnotforme](https://user-images.githubusercontent.com/1138673/39046479-9f3e5d5a-4496-11e8-97b0-0fd19734856c.png)

**Comment by everyoneishappy** [comment]
ah ok.  That was just a test patch whilst making the module, which should have been deleted afterwards.  Will zap it now.  If you're curious to see it that helper module you're missing is pretty much just a normal DX11 rendered + camera
