### ISSUE TITLE
NoiseDerivs2D (3DBuffer).v4p

### ISSUE THREAD

**Issue by circuitb** [everoneishappy/InstanceNoodles#8]
hello Kyle,

there's a bug in the v4p file formatting
https://github.com/everyoneishappy/InstanceNoodles/blob/master/nodes/modules/Compute/Value%20Buffer/NoiseDerivs2D%20(3D%20Buffer)/NoiseDerivs2D%20(3D%20Buffer).v4p
cheers

**Comment by everyoneishappy** [comment]
Would you mind giving this a try?  Tbh I've never used that node...
Should return the noise value in the X component and it's 2D derivatives in the Y & Z

https://www.dropbox.com/sh/o4ttne413hwz7e0/AAA2BOw9ZvljHDOogLDxhlkEa?dl=0

**Comment by circuitb** [comment]
looks good,
just replaced the offfsetXY ioBox to a vector2D one and add a naive help patch!
[NoiseDerivs2D (3D Buffer).zip](https://github.com/everyoneishappy/InstanceNoodles/files/4827689/NoiseDerivs2D.3D.Buffer.zip)
